### ISSUE TITLE
Switch publishing to use the scoped @npr org

### ISSUE THREAD

**Issue by xiehan** [npr/npr-one-api-js-sdk#10]
To help emphasize that this is an officially NPR-owned and distributed package, it probably makes sense to publish future versions as `@npr/npr-one-sdk` instead of the current `npr-one-sdk`. (It's worth noting that the package is already part of the NPR organization on npm, it just isn't being published using the scoped naming convention.)

Since this is a breaking change for consumers, it might make sense to do this around the same time as #9.

When making this change, don't forget to update the README and any other relevant code samples that might be affected by this change.

**Comment by jdickie** [comment]
https://github.com/npr/npr-one-api-js-sdk/pull/17
