### ISSUE TITLE
Change Travis build to include only node.js versions under LTS

### ISSUE THREAD

**Issue by xiehan** [npr/npr-one-api-js-sdk#9]
According to https://github.com/nodejs/Release, the node.js versions currently under LTS are:

* 4.x
* 6.x
* 8.x

In addition to the build, we should update [package.json](https://github.com/npr/npr-one-api-js-sdk/blob/v1.4.0/package.json#L96-L99) and README.md to require a minimum version higher than v0.12.x, which is EOL. Given the fact that active maintenance for 4.x ends in April, it may be worth setting our minimum version at 6.x (or perhaps consider 2 separate releases -- one which supports 4.x as the minimum, and one which supports 6.x).

**Comment by jdickie** [comment]
Should be fixed by [this PR](https://github.com/npr/npr-one-api-js-sdk/pull/16)
